#!/bin/bash

if ! grep -q nix-darwin ~/.nix-channels; then
  echo "https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin" >> ~/.nix-channels
fi
export NIX_PATH=darwin=$HOME/.nix-defexpr/channels/darwin:$NIX_PATH

if ! grep -q home-manager ~/.nix-channels; then
  echo "https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager" >> ~/.nix-channels
fi
# export NIX_PATH=home-manager=$HOME/.nix-defexpr/channels/home-manager:$NIX_PATH

nix-channel --update
export NIX_PATH=darwin-config=$HOME/src/nix/config/darwin.nix:$NIX_PATH

nix-shell '<home-manager>' -A install

echo $NIX_PATH
sudo rm /etc/shells /etc/zprofile
nix-build '<darwin>' -A installer --out-link /tmp/nix-darwin && /tmp/nix-darwin/bin/darwin-installer

# Isn't it supposed to do this? It doesn't.
# rm -rf /run/*

/run/current-system/sw/bin/darwin-rebuild switch
