#+title: Personal Nix Configuration

This is my personal Nix configuration used on MacOS.

* Prerequisites
  1. install [[https://nixos.org/manual/nix/stable/#sect-macos-installation][nix]]
  2. install [[https://github.com/LnL7/nix-darwin][nix-darwin]]
  3. and channel for home-manager
#+begin_src bash
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

nix-channel --update  
#+end_src
     

=note:=
you don't need to install home-manger, nix-darwin will install it instead.

* Setup (Darwin)
- Clone this to ~$HOME/src/nix~

#+begin_src  bash
cd $HOME/src && git clone https://github.com/Eason0210/nix.git 
#+end_src

- Change all the username(aqua0210 is my username) in ~darwin.nix~ and ~home.nix~

- Remove apps you don't need in ~packages.nix~

- Check all the config is good for you and run this command in terminal.

#+begin_src bash
darwin-rebuild switch  
#+end_src

* Other useful commands
#+begin_src bash
  darwin-rebuild --list-generations # list all generations
  darwin-rebuild --rollback # rollback to previous generation
  nix-collect-garbage -d    # remove all other generations except current one
#+end_src

* Install Emacs
  Please refer to [[https://github.com/nix-community/emacs-overlay][nix-community/emacs-verlay]]

- EmacsGit install the master branch of Emacs, recently is Emacs 28.0.50
- Emacs install Emacs latest realease, Emacs 27.2
- EmacsGcc  Install master branch with options ~--with-native-compilation~ enabled

** Pin the version of EmacsGit and EmacsGcc
You need to specify a specific Git revision, along with its hash, in order to avoid re-downloading new versions of the overlay constantly.

Concretely, that means:

1. Change the master string in the url field of builtins.fetchTarball to a specific commit hash.
2. Add a sha256 field to builtins.fetchTarball set to 0000000000000000000000000000000000000000000000000000
3. Try to build (~darwin-rebuild switch~)
4. It will complain about the hash being incorrect (expected zeros, actually the real hash)
5. Replace the zeros with the real hash
...
Profit

refer to [[https://github.com/nix-community/emacs-overlay/issues/170][this issue]].

  
